// ---------------------------------------------------------------------------
// API types — derived directly from backend src/api/schemas.py
// All field names match the wire format (snake_case) exactly.
// ---------------------------------------------------------------------------

/**
 * Request body sent to POST /api/v1/tickets/respond.
 * Mirrors backend: TicketRequest (src/api/schemas.py)
 */
export interface TicketRequest {
  /** Optional subject line for the support ticket. */
  subject?: string;
  /** Full message body. Required; 1–5 000 characters. */
  body: string;
}

/**
 * Successful response from POST /api/v1/tickets/respond.
 * Mirrors backend: TicketResponse (src/api/schemas.py)
 */
export interface TicketResponse {
  /** The queue the ticket was routed to, e.g. "Billing and Payments". Null only on abstention. */
  predicted_queue: string | null;
  /** Draft customer-facing reply generated by the RAG pipeline. Null when needs_human_review=true. */
  generated_answer: string | null;
  /** True when retrieval confidence is below the configured threshold — no LLM answer is generated. */
  needs_human_review: boolean;
  /** Top retrieval similarity score, in [0.0, 1.0]. */
  confidence_score: number;
}

/**
 * Error response shape returned by the backend on 4xx / 5xx.
 * Mirrors the JSONResponse bodies in src/main.py exception handlers.
 */
export interface ApiErrorResponse {
  /** Machine-readable error code, e.g. "bad_gateway" | "internal_server_error". */
  error: string;
  /** Human-readable description. May also be a Pydantic validation detail array on 422. */
  detail: string | unknown[];
}

// ---------------------------------------------------------------------------
// Chat session types — frontend-only, not sent to the API
// ---------------------------------------------------------------------------

export interface ChatMessage {
  id: string;
  role: "user" | "assistant" | "error";
  /** User message text (role = "user"). */
  text?: string;
  /** Parsed API response (role = "assistant"). */
  result?: TicketResponse;
  /** Error description shown to the user (role = "error"). */
  error?: string;
  createdAt: number;
}

export interface Conversation {
  id: string;
  title: string;
  messages: ChatMessage[];
}
